minetest.register_alias("glooptest:table", "glooptest:wooden_table")
minetest.register_node("glooptest:wooden_table", {
    description = "Wooden Table",
    drawtype = "nodebox",
	tiles = {"glooptest_table_tb.png","glooptest_table_tb.png","glooptest_table_side.png"},
	paramtype = "light",
	groups = {choppy=3, snappy=3},
    node_box = {
        type = "fixed",
        fixed = {
            { -8/16, -8/16, -8/16, 8/16, -4/16, 8/16 }, -- base
            { -8/16, 3/16, -8/16, 8/16, 8/16, 8/16 }, -- top
            { 3/16, -7/16, 3/16, 7/16, 7/16, 7/16 },
            { 3/16, -7/16, -7/16, 7/16, 7/16, -3/16 },
            { -7/16, -7/16, 3/16, -3/16, 7/16, 7/16 },
            { -7/16, -7/16, -7/16, -3/16, 7/16, -3/16 },
        },
    },
})

minetest.register_node("glooptest:crystal_glass", {
	description = "Crystal Glass",
	drawtype = "allfaces",
	tiles = {"glooptest_crystal_glass.png"},
	inventory_image = minetest.inventorycube("glooptest_crystal_glass.png"),
	paramtype = "light",
	sunlight_propagates = true,
	groups = {cracky=3},
	sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("glooptest:reinforced_crystal_glass", {
	description = "Steel-Reinforced Crystal Glass",
	drawtype = "allfaces",
	tiles = {"glooptest_reinforced_crystal_glass.png"},
	inventory_image = minetest.inventorycube("glooptest_reinforced_crystal_glass.png"),
	paramtype = "light",
	sunlight_propagates = true,
	groups = {cracky=2},
	sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("glooptest:akalin_crystal_glass", {
    description = "Akalin-Reinforced Crystal Glass",
    drawtype = "allfaces",
    tiles = {"glooptest_akalin_crystal_glass.png"},
    inventory_image = minetest.inventorycube("glooptest_akalin_crystal_glass.png"),
    paramtype = "light",
    sunlight_propagates = true,
    groups = {cracky=2},
    sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("glooptest:heavy_crystal_glass", {
    description = "Heavily Reinforced Crystal Glass",
    drawtype = "allfaces",
    tiles = {"glooptest_reinforced_akalin_crystal_glass.png"},
    inventory_image = minetest.inventorycube("glooptest_reinforced_akalin_crystal_glass.png"),
    paramtype = "light",
    sunlight_propagates = true,
    groups = {cracky=1},
    sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("glooptest:alatro_crystal_glass", {
    description = "Alatro-Reinforced Crystal Glass",
    drawtype = "allfaces",
    tiles = {"glooptest_alatro_crystal_glass.png"},
    use_texture_alpha = true,
    inventory_image = minetest.inventorycube("glooptest_alatro_crystal_glass.png"),
    paramtype = "light",
    groups = {cracky=2},
    sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("glooptest:arol_crystal_glass", {
    description = "Arol-Reinforced Crystal Glass",
    drawtype = "allfaces",
    tiles = {"glooptest_arol_crystal_glass.png"},
    inventory_image = minetest.inventorycube("glooptest_arol_crystal_glass.png"),
    paramtype = "light",
    sunlight_propagates = true,
    groups = {cracky=1},
    sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("glooptest:talinite_crystal_glass", {
    description = "Talinite-Reinforced Crystal Glass",
    drawtype = "allfaces",
    tiles = {"glooptest_talinite_crystal_glass.png"},
    inventory_image = minetest.inventorycube("glooptest_talinite_crystal_glass.png"),
    paramtype = "light",
    sunlight_propagates = true,
    light_source = 14,
    groups = {cracky=2},
    sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("glooptest:mineral_desert_coal", {
    description = "desert coal",
    tiles = {"default_desert_stone.png^default_mineral_coal.png"},
    groups = {cracky=2},
})

minetest.register_node("glooptest:mineral_desert_iron", {
    description = "desert iron",
    tiles = {"default_desert_stone.png^default_mineral_iron.png"},
    groups = {cracky=2},
})

--generated by dump()
minetest.register_node("glooptest:taliniteblock", {
	tiles = {
		"gloopores_talinite_block.png"
	},
	light_source = 14,
	groups = {
		level = 2,
		bendy = 2,
		melty = 2,
		snappy = 1,
		cracky = 1
	},
	description = "Talinite Block"
})
minetest.register_node("glooptest:emeraldblock", {
	tiles = {
		"glooptest_emerald_block.png"
	},
	groups = {
		level = 1,
		bendy = 3,
		cracky = 2
	},
	description = "Emerald Block"
})
minetest.register_node("glooptest:sapphireblock", {
	tiles = {
		"glooptest_sapphire_block.png"
	},
	groups = {
		level = 1,
		bendy = 3,
		cracky = 2
	},
	description = "Sapphire Block"
})
minetest.register_node("glooptest:alatroblock", {
	tiles = {
		"gloopores_alatro_block.png"
	},
	groups = {
		level = 2,
		bendy = 2,
		melty = 2,
		snappy = 1,
		cracky = 1
	},
	description = "Alatro Block"
})
minetest.register_node("glooptest:amethystblock", {
	tiles = {
		"glooptest_amethyst_block.png"
	},
	groups = {
		level = 1,
		bendy = 3,
		cracky = 2
	},
	description = "Amethyst Block"
})
minetest.register_node("glooptest:akalinblock", {
	tiles = {
		"gloopores_akalin_block.png"
	},
	groups = {
		level = 2,
		bendy = 2,
		melty = 2,
		snappy = 1,
		cracky = 1
	},
	description = "Akalin Block"
})
minetest.register_node("glooptest:rubyblock", {
	tiles = {
		"glooptest_ruby_block.png"
	},
	groups = {
		level = 1,
		bendy = 3,
		cracky = 2
	},
	description = "Ruby Block"
})
minetest.register_node("glooptest:topazblock", {
	tiles = {
		"glooptest_topaz_block.png"
	},
	groups = {
		level = 1,
		bendy = 3,
		cracky = 2
	},
	description = "Topaz Block"
})